services:
  api:
    build:
      context: ./api  # Путь к папке с API
    ports:
      - "5000:80"
    networks:
      - app-network

  client:
    build:
      context: ./client  # Путь к папке с клиентом
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
